### PR TITLE
Updated Graphene Requirements

### PR DESCRIPTION
**Pull request by kevinomyonga**
Made updates to graphene requirement versions

graphene==3.1.1
graphene-django==3.0.0
graphql-core==3.2.3

### CODE REVIEW

**Comment by EverWinter23** [comment]
The dependent package requirements are pinned in [setup.py](https://github.com/EverWinter23/graphene-gis/blob/e16f705b0b998b5dfdc4e7fa10a1d659ed7db233/setup.py#L30). These changes only affect `dev` env.

```
    install_requires=[
        "graphene>=3.0.0,<4",
        "graphene-django>=3.0.0b7,<4",
        "graphql-core>=3.1.2,<4",
    ],
```
May I know the problem that this PR is trying to address.

**Comment by kevinomyonga** [comment]
The latest version of graphene-django requires an updated version of
graphene and graphql-core.
The package is causing my project build to fail due to requiring older
versions.

**Comment by EverWinter23** [comment]
Could you please share the error log with me.

**Comment by kevinomyonga** [comment]
It seems the problem was with my docker container. For some reason it is
not throwing the error message anymore.

**Pull request closed without merging**
